### ISSUE TITLE
Does this run on X-Series intel processors which support AVX-512 other than xeon?

### ISSUE THREAD

**Issue by Matheus-Garbelini** [intel/FlexRAN#6]
Dear all, can FlexRAN binaries run on X-Series, Core i7-9800X, Core i9-9900X, and Core i7-11th gen which is described to already support AVX-512 out of the box? It would be interesting to run FlexRan on Consumer PC, but I'm not sure if FlexRan binaries are hardcoded to only run on Xeon or scalable processors.

**Comment by ZhiminYuan11547620** [comment]
Only Xeon server was tested before release.

**Comment by Matheus-Garbelini** [comment]
Thanks @ZhiminYuan11547620 . I'm asking this because Intel Core 9-X is extremely cheaper than buying xeons just for the sake of using SR-IOV for 10gbps ethernet NIC VFs. RRUs are already expensive enough, but Xeon Gold and Platinum can be more expensive than even 2 O-RAN RRUs :-).
